//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Linea_Pedido
    {
        public int PedidoID { get; set; }
        public decimal PrecioPorPlato { get; set; }
        public int PlatoID { get; set; }
        public string Descripcion { get; set; }
        public byte Cantidad { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Plato Plato { get; set; }
    }
}
